app/wed/registry_app/urls.py
from django.conf.urls import *
from django.contrib import admin
from django.contrib.auth.views import logout

admin.autodiscover()


urlpatterns = patterns('registry_app.views',
    (r'^$', 'index'),
    (r'^event/$', 'event'),
    (r'^event/(?P<id>[0-9]+)$', 'event'),
    (r'^event/(?P<event_id>[0-9]+)/invite/$', 'invite'),
    (r'^contact/$', 'contact'),
    (r'^contact/(?P<id>[0-9]+)$', 'contact'),
    (r'^event/(?P<event_id>[0-9]+)/wish/$', 'wish'),
    (r'^event/(?P<event_id>[0-9]+)/wish/(?P<id>[0-9]+)$', 'wish'),
    (r'^guest/(?P<token>[a-zA-Z0-9_\-]+)$', 'guest'),
    (r'^logout_view', 'logout_view'),
)

app/wed/wed/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wed.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('registry_app.urls')),
)

app/wed/registry_app/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from jsonfield import JSONField


# Create your models here.
class Item(models.Model):
    """Wish list item entity."""
    name = models.CharField(max_length=50,
                            verbose_name="Item",
                            help_text="Enter name of wish list item here",
                            blank=True)
    link = models.URLField(max_length=500)
    open_graph = JSONField()
    taken_by = models.EmailField(blank=True)
    event = models.ForeignKey("Event")

    def __unicode__(self):
        return self.name


class Event(models.Model):
    """Occasion entity."""
    time = models.DateTimeField()
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255, blank=True)
    members = models.ManyToManyField(User, related_name="events", through="UserEvent")

    def __unicode__(self):
        return self.title


class UserEvent(models.Model):
    user = models.ForeignKey(User)
    event = models.ForeignKey(Event)
    is_owner = models.BooleanField(default=False)


class Contact(models.Model):
    user = models.ForeignKey(User)
    email = models.EmailField()
    name = models.CharField(blank=True, max_length=100)


class Invite(models.Model):
    contact = models.ForeignKey(Contact)
    event = models.ForeignKey(Event)
    user = models.ForeignKey(User, null=True)
    token = models.CharField(max_length=100)
    sent = models.BooleanField(default=False)


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ["email", "name"]


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ["time", "title", "description"]


class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["link", "taken_by"]

app/wed/registry_app/views.py
import uuid
import base64

from django.http import HttpResponse, HttpResponseRedirect, HttpResponseServerError, Http404
from django.template import RequestContext
from django.template.loader import render_to_string
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from keepboo_opengraph import opengraph
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

from registry_app import models


@login_required
def index(request):
    return redirect("/event")


@login_required
def wish(request, event_id=None, id=None):
    """Manage wish items and stuff"""
    membership, user = get_object_or_404(models.UserEvent, event_id=event_id, user=request.user), request.user
    item = get_object_or_404(models.Item, pk=id) if id else None
    event = membership.event

    go_back = redirect("/event/%s/wish" % event.id)
    action = request.GET.get("act")

    if request.method == "GET" and not action:
        form = models.ItemForm(instance=item) if event else models.ItemForm()

    elif request.method == "POST":
        form = models.ItemForm(request.POST, instance=item) if item else models.ItemForm(request.POST)
        if form.is_valid():
            if item:
                form.save()
            else:
                instance = form.save(commit=False)
                instance.open_graph = opengraph.OpenGraph(url=instance.link)
                event.item_set.add(instance)

            return go_back

    elif request.method == "GET" and action == "del":
        item.delete()
        return go_back

    else:
        raise Http404

    memberships = user.userevent_set.all()
    items = event.item_set.all()

    return render_to_response("wishlist/item.html",
                              {"memberships": memberships,
                               "items": items,
                               "event_id": event.pk,
                               "item_id": item.pk if item else None,
                               "form": form
                               }, RequestContext(request))


@login_required
def event(request, id=None):
    """Add event"""
    membership, user = get_object_or_404(models.UserEvent, event_id=id, user=request.user) if id else None, request.user
    event = membership.event if membership else None

    go_back = redirect("/event")
    action = request.GET.get("act")

    if request.method == "GET" and not action:
        form = models.EventForm(instance=event) if event else models.EventForm()

    elif request.method == "POST" and (not membership or membership.is_owner):
        form = models.EventForm(request.POST, instance=event) if event else models.EventForm(request.POST)
        if form.is_valid():
            instance = form.save()

            if not event:
                membership = models.UserEvent(user=user,
                                       event=instance,
                                       is_owner=True)
                membership.save()

            return go_back

    elif request.method == "GET" and action == "del" and (not membership or membership.is_owner):
        event.delete()
        return go_back

    else:
        raise Http404

    memberships = user.userevent_set.all()

    return render_to_response("wishlist/event.html",
                              {"form": form,
                               "event_id": event.id if event else None,
                               "memberships": memberships}, RequestContext(request))


@login_required
def contact(request, id=None):
    """Create view edit contact"""
    user = request.user
    contact = get_object_or_404(models.Contact, id=id) if id else None
    go_back = redirect("/contact")
    action = request.GET.get("act")

    if request.method == "GET" and not action:
        form = models.ContactForm(instance=contact) if event else models.ContactForm()

    elif request.method == "POST":
        form = models.ContactForm(request.POST, instance=contact) if contact else models.ContactForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = user
            instance.save()
            return go_back
    elif request.method == "GET" and action == "del" and contact.user == user:
        contact.delete()
        return go_back
    else:
        raise Http404
    contacts = user.contact_set.all()
    return render_to_response("contact/contact.html",
                              {"form": form,
                               "contacts": contacts,
                               "contact_id": contact.id if contact else None}, RequestContext(request))


@login_required
def invite(request, event_id):
    """Invite all contacts for event_id (send emails)"""
    user, event = request.user, get_object_or_404(models.Event, id=event_id)
    contacts = user.contact_set.all()

    for contact in contacts:
        instance = models.Invite()
        instance.event = event
        instance.contact = contact
        instance.token = get_a_Uuid()
        instance.save()

        url = "http://81.81.81.6/guest/%s" % instance.token
        html_body = render_to_string("email/invite.html", {"guest_url": url})
        txt_body = render_to_string("email/invite.txt", {"guest_url": url})

        msg = EmailMultiAlternatives('Invitation', txt_body, settings.EMAIL_HOST_USER, [contact.email])
        msg.attach_alternative(html_body, "text/html")
        msg.send()

        instance.sent = True
        instance.save()

    return redirect("/event")


def get_a_Uuid():
    r_uuid = base64.urlsafe_b64encode(uuid.uuid4().bytes)
    return r_uuid.replace('=', '')


def guest(request, token):
    user = request.user

    if not user.is_anonymous():
        # add event to user
        pass
    else:
        # create a user and add him to event
        invite = get_object_or_404(models.Invite, token=token)
        if not invite.user:
            # check if user with this email exists
            user = User.objects.create_user(token, invite.contact.email, token)
            membership = models.UserEvent(user=user,
                                          event=invite.event,
                                          is_owner=False)
            membership.save()
            user = authenticate(username=token, password=token)
            login(request, user)
    return redirect("/event")


@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect("/accounts/login")

app/wed/registry_app/templates/wishlist/event.html
<div id="page-signin-bg">

		<!-- Background overlay -->
		<div class="overlay"></div>
		<!-- Replace this with your bg image -->
		<img src="http://81.81.81.5/static/images/events.jpg" alt="">
	</div>
	<!-- / Page background -->

	<!-- Container -->


{% extends "base.html" %}

{% block content %}

    {% if memberships %}
<div id="main-navbar" class="navbar navbar-inverse" role="navigation">
		<!-- Main menu toggle -->

		<div class="navbar-inner">
			<!-- Main navbar header -->
			<div class="navbar-header">

				<!-- Logo -->
				<a href="index.html" class="navbar-brand">
					<div><img alt="Pixel Admin" src="/static/assets/images/pixel-admin/main-navbar-logo.png"></div>
					Occasion Registry
				</a>

				<!-- Main navbar toggle -->
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

			</div> <!-- / .navbar-header -->

			<div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
				<div>

                    <ul class="nav navbar-nav">
                        <li selected>
							<a href="event_form"><i class="fa fa-plus"></i>&nbsp;&nbsp;&nbsp;&nbsp;<b>New Event</b></a>
						</li>
					    {% for membership in memberships %}
                                <li>
                                    <a href="/event/{{membership.event.id}}/wish/">{{membership.event}}</a>
                                </li>
                                {% endfor %}



					</ul> <!-- / .navbar-nav -->

					<div class="right clearfix">
						<ul class="nav navbar-nav pull-right right-navbar-nav">

<!-- 3. $NAVBAR_ICON_BUTTONS =======================================================================

							Navbar Icon Buttons

							NOTE: .nav-icon-btn triggers a dropdown menu on desktop screens only. On small screens .nav-icon-btn acts like a hyperlink.

							Classes:
							* 'nav-icon-btn-info'
							* 'nav-icon-btn-success'
							* 'nav-icon-btn-warning'
							* 'nav-icon-btn-danger'
-->


							<li>
								<form class="navbar-form pull-left">
									<input type="text" class="form-control" placeholder="Search">
								</form>
							</li>

							<li class="dropdown">
								<a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">

									<span>{{user.username}}</span>
								</a>
								<ul class="dropdown-menu">
									<li><a href="#"><span class="label label-warning pull-right">New</span>Profile</a></li>
									<li><a href="#"><span class="badge badge-primary pull-right">New</span>Account</a></li>
									<li><a href="#"><i class="dropdown-icon fa fa-cog"></i>&nbsp;&nbsp;Settings</a></li>
									<li class="divider"></li>
									<li><a href="/logout_view"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a></li>
								</ul>
							</li>
						</ul> <!-- / .navbar-nav -->
					</div> <!-- / .right -->
				</div>
			</div> <!-- / #main-navbar-collapse -->
		</div> <!-- / .navbar-inner -->
	</div>
<div class="signin-container">


{% endif %}

{% include "wishlist/event_form.html" %}


{% endblock %}
</div>

app/wed/registry_app/templates/wishlist/event_controls.html
								<!-- Success darker background, small padding, vertically aligned text -->
    <a href="/event/{{membership.event.id}}" class="stat-cell bg-success darker padding-sm valign-middle">
									{{membership.event}}

    </a>
    <a href="/event/{{membership.event.id}}/wish/" class="stat-cell bg-info  bordered  no-border-vr no-border-l darker padding-sm valign-middle"> Wish list  <i class="fa fa-edit pull-right"></i></a>

    <a href="/event/{{membership.event.id}}?act=del" class="stat-cell bg-danger darker padding-sm valign-middle">Delete <i class="fa fa-eraser pull-right"></i></a>
    <a href="/event/{{membership.event.id}}/invite" class="stat-cell bg-danger darker padding-sm valign-middle">Invite <i class="fa fa-eraser pull-right"></i></a>
	</a>

app/wed/registry_app/templates/wishlist/event_form.html
<div class="signin-container">
  <!--div class="panel-heading">
    <span class="panel-title">Add event and create a wishlist!</span>
  </div-->
  <div class="panel-body">
    <form class="no-margin" action="/event/{{event_id|default:''}}" method="POST">
      {% csrf_token %}

      <div class="form-group {% if form.time.errors %}has-error{% endif %}">
        <input id="id_time" class="form-control input" placeholder="pick the date and time" name="time" value="{{form.time.value|default_if_none:''}}" type="text">
      </div>

      <div class="form-group {% if form.title.errors %}has-error{% endif %}">
        <input id="id_title" class="form-control input" placeholder="name the ocassion, e.g. Birthday, Wedding, Anniversary" maxlength="100" value="{{form.title.value|default_if_none:''}}" name="title" type="text">
      </div>
       <div class="form-group">
      <input type="submit" class="btn btn-info" value="{% if event_id %}Modify {%else%}Add new {%endif%}event" />
       </div>
    </form>
  </div>
</div>

app/wed/registry_app/templates/wishlist/event_list.html
<div class="panel-transparent">
					<!-- Success background, bordered, without top and bottom borders, without left border, without padding, vertically and horizontally centered text, large text -->
					<a href="/event/" class="stat-cell col-xs-5 bg-success bordered no-border-vr no-border-l no-padding valign-middle text-center text-lg">
						<i class="fa fa-calendar"></i>&nbsp;&nbsp;<strong>Total events: {{memberships.count}}</strong>
					</a> <!-- /.stat-cell -->
					<!-- Without padding, extra small text -->
					<div class="stat-cell col-xs-7 no-padding valign-middle">
						<!-- Add parent div.stat-rows if you want build nested rows -->
						<div class="stat-rows">
							{% for membership in memberships %}
                                <div class="stat-row">
                                {% include "wishlist/event_controls.html"%}
                                </div>
                                {% endfor %}
						</div> <!-- /.stat-rows -->
					</div> <!-- /.stat-cell -->
				</div>

app/wed/registry_app/templates/wishlist/item.html
{% extends "base.html" %}

{% block content %}
{% if memberships %}
<div id="page-signin-bg">

		<!-- Background overlay -->
		<div class="overlay"></div>
		<!-- Replace this with your bg image -->
		<img src="http://81.81.81.5/static/images/background.jpg" alt="">
	</div>

<div id="main-navbar" class="navbar navbar-inverse" role="navigation">
		<!-- Main menu toggle -->

		<div class="navbar-inner">
			<!-- Main navbar header -->
			<div class="navbar-header">

				<!-- Logo -->
				<a href="index.html" class="navbar-brand">
					<div><img alt="Pixel Admin" src="/static/assets/images/pixel-admin/main-navbar-logo.png"></div>
					Occasion Registry
				</a>

				<!-- Main navbar toggle -->
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

			</div> <!-- / .navbar-header -->

			<div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
				<div>

                    <ul class="nav navbar-nav">
                        <li selected>
							<a href="event_form"><i class="fa fa-plus"></i>&nbsp;&nbsp;&nbsp;&nbsp;<b>New Event</b></a>
						</li>
					    {% for membership in memberships %}
                                <li>
                                    <a href="/event/{{membership.event.id}}/wish/">{{membership.event}}</a>
                                </li>
                                {% endfor %}



					</ul> <!-- / .navbar-nav -->

					<div class="right clearfix">
						<ul class="nav navbar-nav pull-right right-navbar-nav">

<!-- 3. $NAVBAR_ICON_BUTTONS =======================================================================

							Navbar Icon Buttons

							NOTE: .nav-icon-btn triggers a dropdown menu on desktop screens only. On small screens .nav-icon-btn acts like a hyperlink.

							Classes:
							* 'nav-icon-btn-info'
							* 'nav-icon-btn-success'
							* 'nav-icon-btn-warning'
							* 'nav-icon-btn-danger'
-->


							<li>
								<form class="navbar-form pull-left">
									<input type="text" class="form-control" placeholder="Search">
								</form>
							</li>

							<li class="dropdown">
								<a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">

									<span>{{user.username}}</span>
								</a>
								<ul class="dropdown-menu">
									<li><a href="#"><span class="label label-warning pull-right">New</span>Profile</a></li>
									<li><a href="#"><span class="badge badge-primary pull-right">New</span>Account</a></li>
									<li><a href="#"><i class="dropdown-icon fa fa-cog"></i>&nbsp;&nbsp;Settings</a></li>
									<li class="divider"></li>
									<li><a href="/logout_view"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a></li>
								</ul>
							</li>
						</ul> <!-- / .navbar-nav -->
					</div> <!-- / .right -->
				</div>
			</div> <!-- / #main-navbar-collapse -->
		</div> <!-- / .navbar-inner -->
	</div>

<div class="signin-container">
{% include "wishlist/item_form.html" %}


{% endif %}

<h1 style="color: white;">Wishlist</h1>
{% include "wishlist/item_list.html" %}
<br>

{% endblock %}

app/wed/registry_app/templates/wishlist/item_controls.html
<!--a href="/event/{{event_id}}/wish/{{item.pk}}">Edit</a>
<a href="/event/{{event_id}}/wish/{{item.pk}}?act=del">Delete</a-->

								<!-- Success darker background, small padding, vertically aligned text -->
    <a href="/event/{{event_id}}/wish/{{item.pk}}" class="stat-cell bg-warning darker padding-sm valign-middle">
									{{item}}
	<i class="fa fa-star pull-right"></i>
    </a>

    <a href="/event/{{event_id}}/wish/{{item.pk}}?act=del" class="stat-cell bg-danger darker padding-sm valign-middle">Delete <i class="fa fa-eraser pull-right"></i></a>
	</a>

app/wed/registry_app/templates/wishlist/item_form.html
<div class="panel">
  <div class="panel-heading">
    <span class="panel-title">Item manager</span>
  </div>

  <div class="panel-body">
    <form class="form-inline" action="/event/{{event_id}}/wish/{{item_id|default:''}}" method="POST">
      {% csrf_token %}
      <div class="form-group {% if form.link.errors %}has-error{% endif %}">
        <input id="id_link" class="form-control input" placeholder="Paste link" value="{{form.link.value|default_if_none:''}}" name="link" type="text">
      </div>
      <input type="submit" class="btn btn-info" value="{%if item_id %} Modify {%else%} Add new {%endif%} item" />
    </form>
  </div>
</div>

app/wed/registry_app/templates/wishlist/item_list.html
	<div id="hero-masonry">
        {% for item in items %}
		<div class="hero-item has-example is-hidden">
			<a href="#">
            <img src="{{ item.open_graph.image }}" />
			<p class="example-title">
				{{ item.open_graph.title }}

      </p>
           </a>
      </div>
      {% endfor %}
		</div>
<script type="text/javascript" src="http://81.81.81.5/static/javascripts/masonry.pkgd.min.js"></script>
<script type="text/javascript">
var container = document.querySelector('#hero-masonry');
var msnry = new Masonry( container, {
  // options
  columnWidth: 100,
  itemSelector: '.hero-item has-example is-hidden'
});
</script>